In [1]:
# import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv('energydata_complete.csv')

In [3]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [6]:
# # determine the important features
# from sklearn.feature_selection import mutual_info_regression, mutual_info_classif

In [7]:
# important = df.drop(['date','Appliances', 'lights'], axis = 1).apply(lambda x: x.corr(df.lights))
# vals= np.argsort(important)
# important[vals]

In [8]:
# df['Appliances'].corr(df.lights)

In [9]:
# cols=df.columns[3:]

# plt.barh(range(len(vals)), important[vals], align='center')
# plt.yticks(range(len(vals)), [cols[i] for i in vals])
# plt.xlabel('Importance')
# plt.show()

In [10]:
# # specify the predicting variables and the target variables
# X = df[df.columns[3:27]]
# Y = df[df.columns[1:3]]
# X.shape, Y.shape

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.model_selection import train_test_split

In [18]:
# from sklearn.metrics import r2_scorefrom sklearn.metrics import r2_score 

# R2 = r2_score(x_1, y_1) 
# print('Coefficient of Determination', R2)

In [19]:
# import numpy
# actual = df['T2']
# predict = df['T6']
 
# corr_matrix = numpy.corrcoef(x_1, y_1)
# # Slice the matrix with indexes [0,1] to fetch the value of coefficient of matrix
# corr = corr_matrix[0,1]
# R_sq = corr**2
 
# print(R_sq)

In [20]:
df.drop(columns = ['date', 'lights'], axis = 1, inplace = True)


In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_norm = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)

In [29]:
y = df_norm['Appliances']
x = df_norm.drop(['Appliances'], axis = 1)


In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [31]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [32]:
y_pred = model.predict(x_test)
y_pred

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [37]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
rmse

0.08751444947661711

In [40]:
R2 = r2_score(y_test, y_pred)
R2

0.14890246319303524

In [34]:
met = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

np.sum(np.square(met['Predicted'] - met['Actual']))

45.34762967266378

In [42]:
from sklearn.linear_model import Ridge

r_reg = Ridge(alpha = 0.4)
r_reg.fit(x_train, y_train)

Ridge(alpha=0.4)

In [44]:
y1_pred = r_reg.predict(x_test)
y1_pred

array([0.03321872, 0.24043824, 0.03461337, ..., 0.06872351, 0.10025536,
       0.05851175])

In [45]:
mse = mean_squared_error(y_test, y1_pred)
rmse = np.sqrt(mse)
rmse

0.08753385704628003

In [54]:
from sklearn.linear_model import Lasso

l_reg = Lasso(alpha = 0.001)
l_reg.fit(x_train, y_train)
wght = pd.Series(l_reg.coef_, x_train.columns).sort_values()
df_wght = pd.DataFrame(wght)
df_wght.columns = ['Lasso Weight']
df_wght

Lasso Weight
RH_out          -0.049557
RH_8            -0.000110
T1               0.000000
Tdewpoint        0.000000
Visibility       0.000000
Press_mm_hg     -0.000000
T_out            0.000000
RH_9            -0.000000
T9              -0.000000
T8               0.000000
RH_7            -0.000000
rv1             -0.000000
T7              -0.000000
T6               0.000000
RH_5             0.000000
T5              -0.000000
RH_4             0.000000
T4              -0.000000
RH_3             0.000000
T3               0.000000
RH_2            -0.000000
T2               0.000000
RH_6            -0.000000
rv2             -0.000000
Windspeed        0.002912
RH_1             0.017880

In [56]:
ylasso_pred = l_reg.predict(x_test)
ylasso_pred

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [57]:
mse = mean_squared_error(y_test, ylasso_pred)
rmse = np.sqrt(mse)
rmse

0.09358170467245137